# Generated by Django 2.0 on 2020-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCall',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('phoneNumber', models.CharField(max_length=256)),
                ('duration', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('mediaUrl', models.CharField(max_length=256)),
                ('callType', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
